<a href="https://colab.research.google.com/github/gaby1719/etl-data-pipeline/blob/main/clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/gaby1719/datawarehouse-seguros.git

In [ ]:
import pandas as pd

BLOQUE 1: CARGA DEL DATASET

In [ ]:
#Ruta del dataset almacenada en GitHub
url = "https://raw.githubusercontent.com/gaby1719/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [ ]:
#Lectura del Archivo
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [ ]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2: Exploración del DATASET

In [ ]:
print("Primeras filas del dataset")
display(df.head())

Primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [ ]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(3030, 7)

In [ ]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [ ]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [ ]:
print("Valores nulos por columnas")
print(df.isnull().sum())

Valores nulos por columnas
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [ ]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [ ]:
#Elimionar espacios al inicio y al final del texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [ ]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [ ]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [ ]:
#Normalizar genero
df["genero"]=df["genero"].str.upper()

In [ ]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [ ]:
#Normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()
df['ciudad']=df['ciudad'].astype(str)
df['ciudad']=df['ciudad'].str.strip()
df['ciudad']=df['ciudad'].str.upper()

In [ ]:
#Limpieza de segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

In [ ]:
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

BLOUQE 4:VALIDACIÓN DE DATOS

In [ ]:
#Crear columna para registrar errores
df["motivo_rechazo"] = ""

#validar id_cliente
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"] += "id_cliente nulos; "

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

DB_URL = "postgresql://etl_user:JAb9JP6gRc0RyRTCpEHmyb9prPFT7B4o@dpg-d6qu6r7gi27c73aaadlg-a.oregon-postgres.render.com/etl_seguros_68ir"
engine = create_engine(DB_URL)

In [2]:
engine = create_engine(DB_URL)

query_create = """
CREATE TABLE clientes(

id_cliente INT PRIMARY KEY,

nombre VARCHAR(150),

email VARCHAR(150),

genero VARCHAR(20),

fecha_nacimiento DATE,

ciudad VARCHAR(100),

segmento VARCHAR(50)

);
"""

try:
    with engine.connect() as connection:
        connection.execute(text(query_create))
        connection.commit()
        print("¡Tabla 'polizas' creada exitosamente en Render!")
except Exception as e:
    print(f"Error al crear la tabla: {e}")

¡Tabla 'polizas' creada exitosamente en Render!